name: Auto Update Status X

on:
  schedule:
    - cron: '*/5 * * * *'  # Jalan setiap 5 menit
  workflow_dispatch:

jobs:
  update-status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install tweepy

      - name: Update status on X
        env:
          API_KEY: ${{ secrets.X_API_KEY }}
          API_SECRET: ${{ secrets.X_API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.X_ACCESS_TOKEN_SECRET }}
        run: |
          python auto_update_status_x.py
